### ISSUE TITLE
Improve the XML parser

### ISSUE THREAD

**Issue by mephenor** [sbmlteam/jsbml#108]
try to improve the current parser or use an other parser to simplify the code (xstream is a good candidate)

it need to :
- use reflection to see if an isSetXXX methods exist and use it before writing the XXX attributes
- be able to read / write the ListOfXXX without too much code
- be able to save / print part of a Model
- be relatively quick when reading / writing large models (more than 10MB)
- work well with namespaces
- make it easy to add support for a level 3 package
- be able to parse and wrote elements that it doesn't know

Reported by: niko-rodrigue

**Comment by niko-rodrigue** [comment]
Most of those points are now in place, apart for  "be able to save / print part of a Model" but this feature could be implemented without too much effort, It think. And it is linked to the toSBML() method issue (see #98) . So closing this issue.
