### ISSUE TITLE
Include a parser for the MIRIAM XML file

### ISSUE THREAD

**Issue by mephenor** [sbmlteam/jsbml#118]
It is often difficult to interpret the meaning of MIRIAM-compliant URNs. The MIRIAM project provides a special XML file that allows translating a MIRIAM URN into a list of existing URL. It would be nice if JSBML could offer a function that simply returns all actual URLs for each URN within a MIRIAM annotation of some element.

Reported by: *anonymous

**Comment by niko-rodrigue** [comment]
On a separate project, we did develop a local library that allow to do all of that and all of what the miriam web services are providing. See https://sourceforge.net/p/identifiers-org/code/HEAD/tree/registry-lib/
