### ISSUE TITLE
Easier access to qualfiers information

### ISSUE THREAD

**Issue by mephenor** [sbmlteam/jsbml#122]
The following methods to accessing information about the qualifiers used in CVTerms would be highly appreciated (name given for indication purposes only):

\* Get the qualifier's name
for example: cvterm.getModelQualifier().getName()
which would return 'isDescribedBy', 'is', 'occursIn', ...

\* Get qualifier's type
for example: cvterm.getModelQualifier().getType()
which could return 'model' or 'biology'

The fact to need to do:
if (cvterm.getQualifierType().toString().equals("MODEL_QUALIFIER"))
{
do something
}
else
{
do something else
}

is really cumbersome.

Thanks.

Reported by: perkeo

**Comment by niko-rodrigue** [comment]
We did improve the CVTerm API, although all of the old methods are still there to allow retro-compatibility with old code.
