### ISSUE TITLE
SBMLDocument.getNumErrors() return 0 even when having errors

### ISSUE THREAD

**Issue by mephenor** [sbmlteam/jsbml#123]
A huge problem with the current jsbml version.
The getNumErrors() function of the SBMLDocument class always retrun 0...
So it is impossible to test if a readed SBML model has errors or no..

It can be tested with the following really simple function:

File f = new File("model.xml");
try
{
SBMLReader reader   = new SBMLReader();
SBMLDocument doc    = reader.readSBML(f);
System.out.println(doc.getNumErrors());
}
catch (Exception e){e.printStackTrace();}

if you need an SBML file with errors to test, you can download this one: http://www.biomedcentral.com/content/supplementary/1471-2164-11-202-s2.xml

Also, another remark concerning the behavior of jsbml concerning parsing errors.
Currently, if a model, a reaction or a species as an incorrect identifier like for example "M_PIn-1_c" (that contains a dash): 
the library return the error:

ERROR (SBMLCoreParser.java:328) - "M_PIn-1_c" is not a valid identifier for this species.

but unfortunately, the corresponding species would be created with an empty ID, which pose many problems. It would be preferable to create the species with its original ID (or its original ID with all non allowed characters removed or replaced by a "_") so that we could still be able to manipulate and export the model (with a warning saying that the ID does not fulfill SBML requirements, if we have keep it as it is) if we want to.
This is  a really problematic issue as many published models does actually not respect the SBML specifications so it is impossible to read them correctly with JSBML (many objects have resulting empty IDs and it is impossible to trace back who is who...) 

Reported by: *anonymous

**Comment by niko-rodrigue** [comment]
With the start of the implementation of a pure JSBML validator, we did relax many checks when reading a model so that we are able to read the model as it is to do a proper and complete validation.
So the reported problem with empty id when there are duplicated id won't happen any more.
