### ISSUE TITLE
Pivotal tracker in README.md links to wrong project

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/jsbml#134]
Hi,
I just wanted to have a look on how JSBML is handling the issue tracking.
Clicking on the link in the README.md leads to the MOCCASIN tracker:
Pivotal tracker: https://www.pivotaltracker.com/n/projects/977060

Related to this I have the following question:
- How do other COMBINE projects track their issues? Also via pivotal tracker? I am looking for something to replace the old sourceforge tracker for SED-ML. If SBML and JSBML already use pivotal this would be the system of choice.

Best
Matthias

**Comment by niko-rodrigue** [comment]
Thanks, I have corrected the link. I will follow up on your question by email with the whole sbml-team.

**Comment by luciansmith** [comment]
I can respond to your related question--the SBML team does indeed use
pivotal for all its issue tracking needs.  However, the SBML specification
uses sourceforge.  And, actually, when people who are not on the team
submit issues about libsbml, they usually use sourceforge as well. Then we
transfer them to pivotal!

Of sourceforge, pivotal, and github, I personally like the pivotal
interface the best, with sf next, and github least. But github is probably
growing to be the most common/familiar to people.  I would let people
submit issues however they see fit (any tracker/email/in person) and then
enter those issues in whatever tracker we want to 'bless' as the main one.

-Lucian
