### ISSUE TITLE
Add a function for the conversion of ASTNodes to GPRs

### ISSUE THREAD

**Issue by draeger** [sbmlteam/jsbml#139]
@tpfau requested to move the code from [ModelPolisher](https://github.com/SBRG/ModelPolisher) to JSBML to make it easier for users to convert parsed `ASTNode` objects to `GeneProductAssociations`. While the class `CobraFormulaParser` provides already methods for reading logical rules in [COBRA](https://github.com/opencobra/)-format, it is not always straightforward to convert those to proper `GeneProteinAssociations` objects. ModelPolisher has a function `parseGPR` for this purpose in its [`SBMLUtils`](https://github.com/SBRG/ModelPolisher/blob/master/src/edu/ucsd/sbrg/util/SBMLUtils.java) class. This could be migrated to JSBML directly.

**Comment by niko-rodrigue** [comment]
You should put it in the CobraUtils class.

**Comment by niko-rodrigue** [comment]
@draeger Do you think, you would have time to do that before next week, to include it in the next release ?

**Comment by mephenor** [comment]
Should be done by tomorrow evening

**Comment by mephenor** [comment]
The parseGPR code depends on code in the fbc extension. 
Additionally Intellij warns me against importing code from there:

    Adding dependency on module 'jsbml-fbc' will introduce circular dependency between modules 'jsbml-core' and 'jsbml-fbc'.

Wouldn't it be better to place the code with the fbc source?

**Comment by niko-rodrigue** [comment]
Yes, if it depends on FBC, you should put it there (inside
extensions/fbc/src).

**Comment by mephenor** [comment]
Added it to  extensions/fbc/src/org/sbml/jsbml/ext/fbc/converters as GPRParser.java.
In its current state its a direct copy of the ModelPolisher code, with a few necessary changes.
Would be nice if someone could have a quick look at it with regard to:
- Access modifiers
- Formatting
- Whether 'omitGenericTerms' is necessary in this context

There is no real JavaDoc, so maybe I'll need to do something there.
