### ISSUE TITLE
setSBOTerm with null value throws NPE

### ISSUE THREAD

**Issue by piotr-gawron** [sbmlteam/jsbml#143]
When I try to set String SBOTerm that is null I get NullPointerException. You can find  the code below.
I think that instead of NPE SBOTerm should be removed from the node on which method was called.

```
SBMLDocument doc = new SBMLDocument(3, 1);
Model model = doc.createModel("test_model");
String term = null;
model.setSBOTerm(term);
```

**Comment by draeger** [comment]
Fixed. Thanks for pointing this out!
