### ISSUE TITLE
Problems converting ASTNode2 to ASTNode with FormulaParserLL3

### ISSUE THREAD

**Issue by LisaFalk** [sbmlteam/jsbml#147]
Even though it is not the best idea converting ASTNode2 to ASTNode with FormulaParserLL3 we thought it would be working.
But the formula (A xor B) causes the following exception:
Caused by: org.sbml.jsbml.text.parser.ParseException: Encountered " "xor "" at line 1, column 3.
Was expecting one of:

"+" ...
"^" ...
"-" ...
"*" ...
"/" ...
"%" ...
...
<BOOLEAN_LOGIC> ...
...

**Comment by niko-rodrigue** [comment]
Thanks for the report, in fact, to support easily 'xor(A, B)' we removed the support for 'A xor B'. You can still use 'XOR' or 'Xor'. Did you wrote this by hand or was it generated by one of the FormulaCompiler ?

**Comment by LisaFalk** [comment]
Thank you. It occured by calling the method toFormula() on a ASTLogicalOperatorNode(ASTNode.Type.LOGICAL_XOR).

**Comment by niko-rodrigue** [comment]
Yes, the ASTNode2 formula compiler would not have been corrected with the latest changes, I will take care of that.

**Comment by niko-rodrigue** [comment]
It should be fixed now in master.
