### ISSUE TITLE
Building javadoc fails (at least on macOS)

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/jsbml#207]
I am unable to run `ant javadoc` successfully using Apache Ant version 1.10.7 on a mac 10.13.6 system. It prints a lot of messages and gets to a point where it prints

    [javadoc] Constructing Javadoc information...
    [javadoc] 1 error
    [javadoc] javadoc: error - Argument for -header contains JavaScript.
    [javadoc] Use --allow-script-in-comments to allow use of JavaScript.

and then claims `BUILD SUCCESSFUL` but this is a lie; the `apidocs` directory is empty and the process printed other errors earlier.

After repeatedly trying to adjust `build.xml`, I found that not only the max number of warnings and errors be increased, but also memory must be increased, and the option `--allow-script-in-comments` be added to Javadoc.

**Comment by mhucka** [comment]
This is the Java version info via `java -version`:
```
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
```

**Comment by niko-rodrigue** [comment]
Merged you fix.
