### ISSUE TITLE
package org.mangosdk.spi does not exist - project does not compile

### ISSUE THREAD

**Issue by Schmoho** [sbmlteam/jsbml#261]
Hi.
I've just cloned the repo to have a look into how much of an effort it would be to fix https://github.com/sbmlteam/jsbml/issues/217 because it is a nuisance in the downstream consuming https://github.com/draeger-lab/ModelPolisher

Apart from the issue that it is actually quite hard to get a hold of a JRE 1.7 this time around, the project as is does not compile at all (for me) because the package org.mangosdk.spi is not available anywhere.

 `mvn dependency:resolve `checked 
https://repo.maven.apache.org/maven2
https://github.com/biojava/maven-repo/raw/master/
https://www.ebi.ac.uk/~maven/m2repo 

and couldn't find it.

**Comment by draeger** [comment]
What exactly goes wrong in ModelPolisher because of JSBML’s dependency on log4j?

**Comment by Schmoho** [comment]
I had some trouble in the server implementation where jsbml would sometimes capture all logs and write them to a file, instead of them going to stdout. I figured out how to override this behaviour downstream though, so I guess this isn't an issue anymore.

I also realized the ant build script seems to work still, so I apologize and think this issue is closed.
