### ISSUE TITLE
Encoding error in org.sbml.jsbml.xml.stax.SBMLWriter

### ISSUE THREAD

**Issue by mephenor** [sbmlteam/jsbml#87]
The method "writeSBMLToString(SBMLDocument, String, String)" does not do the encoding right, when the standard charset on the computer is not UTF-8 (e.g. on Windows).

return stream.toString();

should be replaced by

return stream.toString("UTF-8");

Reported by: cthoens

**Comment by niko-rodrigue** [comment]
This was fixed some time ago, thanks for the report.
