### ISSUE TITLE
Incorrect date in output SBML

### ISSUE THREAD

**Issue by mephenor** [sbmlteam/jsbml#91]
I exported SBML using new SBMLWriter("MyApp","1.0") ...

The output has the wrong month in the second line:

<?xml version='1.0' encoding='UTF-8' standalone='no'?>

I'm sure this is a simple fix where the format specifier for the minute was used where the month was supposed to go; notice the month and the minute are the same... this is always true in all the SBML files I've generated.

Reported by: *anonymous

**Comment by niko-rodrigue** [comment]
This is fixed. The minutes were written instead of the month in the date.
